### ISSUE TITLE
latest version?

### ISSUE THREAD

**Issue by harphere** [arpruss/xupdown#1]
Hi, found this through XDA but can't find the latest version of the apk.
The releases tab has an apk from March 2015 but there must be something newer?

**Comment by arpruss** [comment]
I think it's in the official xposed collection of modules, but I don't know where that is now.

**Comment by harphere** [comment]
I found the Lsposed official repo here:
https://modules.lsposed.org/
https://github.com/Xposed-Modules-Repo
Do you mind adding it?

**Comment by arpruss** [comment]
Is the old location permanently down? Right now it seems down: http://repo.xposed.info/module/mobi.omegacentauri.xupdown

**Comment by arpruss** [comment]
You can also get it direct from github:
https://github.com/arpruss/xupdown/blob/master/app/release/app-release.apk?raw=true

**Comment by harphere** [comment]
> Is the old location permanently down? Right now it seems down: http://repo.xposed.info/module/mobi.omegacentauri.xupdown

It seems permanently down, yes. Adding it to Lsposed repo would definitely help.

**Comment by harphere** [comment]
> You can also get it direct from github: https://github.com/arpruss/xupdown/blob/master/app/release/app-release.apk?raw=true

Got it, thank you.
